[package]
name = "svgrust"
version = "0.1.0"
edition = "2021"

[lib]
name = "plt"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.79"
cargo-watch = "8.5.2"
clap = { version = "4.4.17", features = ["derive"] }
geo = "0.27.0"
rand = "0.8.5"
svg = "0.14.0"
